# .github/workflows/firebase-deploy.yml
name: Deploy to Firebase

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies and Build
        run: |
          npm install --force
          npm run build

      - name: Firebase Deploy
        run: |
          npm install -g firebase-tools
          firebase deploy --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
